name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: |
          sudo apt update
          sudo apt install libevdev-dev libdbus-1-dev
      - name: build
        run: make

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: |
          sudo apt update
          sudo apt install libevdev-dev libdbus-1-dev
      - name: test
        run: make test
