name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install libevdev-dev libdbus-1-dev
      - name: Build
        run: make

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install libevdev-dev libdbus-1-dev
      - name: Test
        run: make test
